baseurl         = "https://www.abrahamlaria.com"
theme           = "casper-two"
languageCode    = "en-US"
disqusShortname = "abrahamlaria"
paginate        = 6
contentdir      = "content"
enableRobotsTXT = true
#hjsStyle = "Darcula"
#SectionPagesMenu = "main"

[params]
  title       = "Abraham Laria Blog"
  subtitle    = "Thougts on software construction and leadership"

  cover       = "uploads/cover.jpg"
  description = "Abraham Laria's Blog about software architecture, coding and management."
  metaDescription = ""
  googleAnalytics = "UA-31663616-1"
  customCSS = []
  RSSLink = ""

 
  linkedinName = "abrahamlaria"
  githubName = "abrahamlaria"
  twitterName = "abrahamlaria"
  mediumName = "abrahamlaria"


  logo = ""
  orgName = "AL"
  orgWebsite = "https://abrahamlaria.com"
  orgDescription = "Here is a description placeholder for your org"

  author = "Abraham Laria"
  authorAvatar = "uploads/avatar.png"
  authorLocation = "Las Vegas, NV"
  authorWebsite = "https://abrahamlaria.com"
  authorDescription = "Sr. Software Engineer at Pinnacle Entertainment Inc. Aspiring solution architect. Interested in team management."

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/:slug/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200

[[menu.main]]
  name = "Architecture"
  url = "/architecture/"
  weight = 100

[[menu.main]]
  name = "Development"
  url = "/development/"
  weight = 99

[[menu.main]]
  name = "Management"
  url = "/management/"
  weight = 95
