PygmentsCodeFences = true
PygmentsStyle = "monokai"
baseurl = "https://www.abrahamlaria.com"
contentdir = "content"
disqusShortname = "abrahamlaria"
enableRobotsTXT = true
languageCode = "en-US"
paginate = 6
theme = "casper-two"
[[menu.main]]
name = "Management"
url = "/management/"
weight = 1
[[menu.main]]
name = "Development"
url = "/development/"
weight = 2
[[menu.main]]
name = "Architecture"
url = "/architecture/"
weight = 3
[params]
RSSLink = ""
author = "Abraham Laria"
authorAvatar = "uploads/avatar.png"
authorDescription = "Sr. Software Engineer at Pinnacle Entertainment Inc. Aspiring Solution Architect, interested in Team Management."
authorLocation = "Las Vegas, NV"
authorWebsite = "https://abrahamlaria.com"
cover = "uploads/cover.jpg"
customCSS = []
description = "Abraham Laria's Blog about software architecture, coding and management."
githubName = "abrahamlaria"
googleAnalytics = "UA-31663616-1"
linkedinName = "abrahamlaria"
logo = ""
mediumName = "abrahamlaria"
metaDescription = ""
orgDescription = ""
orgName = "AL"
orgWebsite = "https://abrahamlaria.com"
pageNotFoundTitle = "404 - Page not found"
singleViewStyle = "casper"
subtitle = "Thougts on software construction and leadership"
title = "The Coder One"
twitterName = "abrahamlaria"
[permalinks]
post = "/:slug/"
