PygmentsCodeFences = true
PygmentsStyle = "monokai"
<<<<<<< HEAD
#SectionPagesMenu = "main"

[params]
  title       = "The Coder One"
  subtitle    = "Thougts on software construction and leadership"

  cover       = "uploads/cover.jpg"
  description = "Abraham Laria's Blog about software architecture, coding and management."
  metaDescription = ""
  googleAnalytics = "UA-31663616-1"
  customCSS = []
  RSSLink = ""

 
  linkedinName = "abrahamlaria"
  githubName = "abrahamlaria"
  twitterName = "abrahamlaria"
  mediumName = "abrahamlaria"


  logo = ""
  orgName = "AL"
  orgWebsite = "https://abrahamlaria.com"
  orgDescription = ""

  author = "Abraham Laria"
  authorAvatar = "uploads/avatar.png"
  authorLocation = "Las Vegas, NV"
  authorWebsite = "https://abrahamlaria.com"
  authorDescription = "Sr. Software Engineer. Aspiring Solution Architect, interested in Team Management."

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/:slug/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200

=======
baseurl = "https://www.abrahamlaria.com"
contentdir = "content"
disqusShortname = "abrahamlaria"
enableRobotsTXT = true
languageCode = "en-US"
paginate = 6
theme = "casper-two"
>>>>>>> 7cce6c60b00f68f5056eede0a2cc898174e097d4
[[menu.main]]
name = "Management"
url = "/management/"
weight = 1
[[menu.main]]
name = "Development"
url = "/development/"
weight = 2
[[menu.main]]
name = "Architecture"
url = "/architecture/"
weight = 3
[params]
RSSLink = ""
author = "Abraham Laria"
authorAvatar = "uploads/avatar.png"
authorDescription = "Sr. Software Engineer at Pinnacle Entertainment Inc. Aspiring Solution Architect, interested in Team Management."
authorLocation = "Las Vegas, NV"
authorWebsite = "https://abrahamlaria.com"
cover = "uploads/cover.jpg"
customCSS = []
description = "Abraham Laria's Blog about software architecture, coding and management."
githubName = "abrahamlaria"
googleAnalytics = "UA-31663616-1"
linkedinName = "abrahamlaria"
logo = ""
mediumName = "abrahamlaria"
metaDescription = ""
orgDescription = ""
orgName = "AL"
orgWebsite = "https://abrahamlaria.com"
pageNotFoundTitle = "404 - Page not found"
singleViewStyle = "casper"
subtitle = "Thougts on software construction and leadership"
title = "The Coder One"
twitterName = "abrahamlaria"
[permalinks]
post = "/:slug/"
